### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by mati4458** [adrianodds/olx.pt_crawler#1]
Could you help me set this crawler? I have submitted Gmail email and password in olx_funcoes.py, enabled everything as shown:
![image](https://user-images.githubusercontent.com/14836704/201663649-87109176-719d-4445-b3f0-8c0cb4beec17.png)
![image](https://user-images.githubusercontent.com/14836704/201664554-a3df44da-e29c-42a7-9332-09ef9bb0266c.png)
![image](https://user-images.githubusercontent.com/14836704/201664903-fdfcb593-1a66-4d21-b683-67a3685871d7.png)
![image](https://user-images.githubusercontent.com/14836704/201665599-2883b7fe-500e-4ecd-bb5f-cb20c8fb9f49.png)

I still get:

> <Element html at 0x191e61f9400>
<Element html at 0x191e6c3a900>
<Element html at 0x191e6ce9d00>
Em execução..
Traceback (most recent call last):
  File "C:\Users\werom\OneDrive\Pulpit\olx.pt_crawler-main\main.py", line 44, in <module>
    olx_funcoes.email(olx_funcoes.enderecos_email(),(f"Corre!!! OLX! - {titulo + ' - ' + valor}"), (f"{corpo_email}"))
  File "C:\Users\werom\OneDrive\Pulpit\olx.pt_crawler-main\olx_funcoes.py", line 30, in email
    smtp.login(email_address, email_passowrd)
  File "C:\Python310\lib\smtplib.py", line 750, in login
    raise last_exception
  File "C:\Python310\lib\smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "C:\Python310\lib\smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials 24-20020ac24838000000b004a2550db9ddsm1795003lft.245 - gsmtp')

**Comment by adrianodds** [comment]
Olá mati4454, é necessário gerar um token para que seja possível enviar e-mail por Gmail, para isso, a verificação de duas etapas deve estar ativa. Em seguida, nas configurações de segurança da sua conta google, logo abaixo da verificação por duas etapas está a opção senhas de app:

basta acessar essa opção, gerar um token e informar no campo password do código.

![image](https://user-images.githubusercontent.com/42756875/202197432-3256aa9d-7ab7-4f1e-b1d5-b06c080900d8.png)
![image](https://user-images.githubusercontent.com/42756875/202198202-64c3b3e9-6cb9-498a-b6dd-9fd7848ce48a.png)

**Comment by mati4458** [comment]
Thanks a lot, now it works flawlessly!
